//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperEmailValidator.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuperEmailValidator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 0-00.usa.cc
        ///0-180.com
        ///0-30-24.com
        ///0-420.com
        ///0-900.com
        ///0-aa.com
        ///0-attorney.com
        ///0-mail.com
        ///0-z.xyz
        ///0.mail.mujur.id
        ///0.pbot.tk
        ///00-tv.com
        ///00.msk.ru
        ///00.pe
        ///000000pay.com
        ///00043015.com
        ///000476.com
        ///000521.xyz
        ///000777.info
        ///00082aa.com
        ///00082cc.com
        ///00082dd.com
        ///00082ff.com
        ///00082ii.com
        ///00082mm.com
        ///00082rr.com
        ///00082ss.com
        ///00082uu.com
        ///00082xx.com
        ///00082zz.com
        ///000865b.com
        ///000865e.com
        ///000865g.com
        ///000865j.com
        ///00093015.com
        ///0009827.com
        ///0009837.com
        ///000av.app
        ///000br88.com
        ///000email.com
        ///000xxoo.co [stringa troncata]&quot;;.
        /// </summary>
        internal static string disposable_mail_domain_list {
            get {
                return ResourceManager.GetString("disposable_mail_domain_list", resourceCulture);
            }
        }
    }
}
